name:  Bug Report
description: File a bug report
title: Template
body:
  - type: markdown
    attributes:
      value: |
        Before you begin

  - type: dropdown
    id: _branches
    attributes:
      label: Repository Branches
      description: Fetched by action
      options:       
        - main
        - safeguard
        - set-output
    validations:
      required: true  

  - type: dropdown
    id: _releases
    attributes:
      label: Repository releases
      description: Fetched by action
      options:       
        - v1.0        
    validations:
      required: true      
