name: Bug Report
description: File a bug report
title: Template
body:
  - type: markdown
    attributes:
      value: |
        Before you begin
  - type: dropdown
    id: _branches
    attributes:
      label: Repository Branches
      description: Fetched by action
      options:
        - first
        - main
        - second
        - test
    validations:
      required: true
