name: Issue Template for Deployment
description: Issue for Deployment process
title: Deployment Issue
body:
  - type: markdown
    attributes:
      value: |
        Please fill below information for deployment
  - type: dropdown
    id: _branches
    attributes:
      label: Repository Branches
      description: Branches to deploy
      options:
        - KalpanaReddyC-patch-1
        - first
        - main
        - sec
        - second
        - test
    validations:
      required: true
  - type: dropdown
    id: _environments
    attributes:
      label: Environment
      description: Environment to deploy
      options:
        - dev
        - qa
    validations:
      required: true
  - type: dropdown
    id: _releases
    attributes:
      label: Repository releases
      description: Releases to deploy
      options:
        - v10     February 07 2024
        - v8.0     February 07 2024
        - v7.0     February 07 2024
        - 6     February 07 2024
        - v4.0     February 07 2024
        - v3.0     February 06 2024
        - v2.0     February 06 2024
        - v1.0     February 06 2024
    validations:
      required: true
