name: 🚀 Update Issue template

on:  
  workflow_dispatch:  
  release:
    types: [published, deleted] 

jobs:
  # branch_event:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     branch_event_type: ${{ steps.branch_eventType.outputs.result }}
  #   steps:
  #     - name: Check if branch was created or deleted
  #       id: branch_eventType
  #       run: |
  #        echo ${{ github.event_name }}
  #        echo ${{ github.event.ref_type }}

  #        #if event is for release or branch
  #        if [ "${{ github.event_name }}" == "release" ]; then
  #           echo "result=true" >> "$GITHUB_OUTPUT"
  #         elif [ "${{ github.event_name }}" == "create" ]; then
  #           echo "result=true" >> "$GITHUB_OUTPUT"
  #         elif [ "${{ github.event_name }}" == "delete" ]; then
  #           echo "result=true" >> "$GITHUB_OUTPUT"
  #         else
  #           echo "result=false" >> "$GITHUB_OUTPUT"
  #         fi

  pre:
    name: Prepare context for other jobs
    runs-on: ubuntu-latest
    #check if above job output value is branch
    # needs: branch_event
    # if: ${{ needs.branch_event.outputs.branch_event_type == 'true' }}
    outputs:
      # needed in order to reference the local action
      branch: ${{ steps.branch.outputs.job_ref }}
      branches: ${{ steps.branches.outputs.result }}
      releases: ${{ steps.releases.outputs.result }}
      environments: ${{ steps.environments.outputs.result }}
    
    steps:
      - name: Setting branch for committing
        id: branch
        run: |
          BRANCH=""
          if [ ${{ github.event_name == 'release' }} == true ]; then
            BRANCH=${{ github.event.release.target_commitish || github.sha }}
          elif [ ${{ github.event_name == 'create' }} == true ]; then
            BRANCH=${{ github.event.repository.default_branch }}
          elif [ ${{ github.event_name == 'pull_request' }} == true ]; then
            BRANCH=${{ github.head_ref }}
          else
            BRANCH=${{ github.ref }}
          fi
          echo "job_ref=$BRANCH" >> $GITHUB_OUTPUT
          echo "Branch: $BRANCH"

      - name: Get branches
        id: branches
        uses: actions/github-script@v6
        with:
          result-encoding: string
          # https://octokit.github.io/rest.js
          # https://docs.github.com/en/rest/branches/branches#list-branches
          script: |
            return github
              .rest.repos.listBranches(context.repo)
              .then((res) => res.data.map((b) => b.name));

      - name: Get releases
        id: releases
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            return github
              .rest.repos.listReleases(context.repo)
              .then((res) => {
                const releases = res.data.map((r) => `${r.tag_name} ${new Date(r.created_at).toLocaleDateString('en-US', { month: 'long', day: '2-digit', year: 'numeric' }).replace(',', '')}`);
                console.log(releases);
                return releases;
              });

      - name: Get environments
        id: environments
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            return github
              .rest.repos.getAllEnvironments(context.repo)
              .then((res) => {
                const environments = res.data.environments;
                console.log(environments);
                return environments ? environments.map((b) => b.name) : [];
              });    

  update-bug-report:
    name: Update bug report on branch `${{ needs.pre.outputs.branch }}`
    runs-on: ubuntu-latest
    needs: pre
    if: contains(github.actor, 'github-actions') == false
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ needs.pre.outputs.branch }}

      - name: Update branches
        id: branches
        uses: ./actions/update-issue-form-template
        with:
          form: .github/ISSUE_TEMPLATE/issue_template.yml
          dropdown: _branches
          options: ${{ needs.pre.outputs.branches }}
          dry_run: no-push

      - name: Update releases
        id: releases
        uses: ./actions/update-issue-form-template
        with:
          form: .github/ISSUE_TEMPLATE/issue_template.yml
          dropdown: _releases
          options: ${{ needs.pre.outputs.releases }}
          dry_run: no-push

      - name: Print environment
        run: echo ${{ needs.pre.outputs.environments }}

      - name: Update environments
        id: environments
        uses: ./actions/update-issue-form-template
        if: ${{ needs.pre.outputs.environments != '[]' }}
        with:
          form: .github/ISSUE_TEMPLATE/issue_template.yml
          dropdown: _environments
          options: ${{ needs.pre.outputs.environments }}
          dry_run: no-push
    